### PR TITLE
Fix: add php-cli to PATH

### PR DESCRIPTION
**Pull request by till**
Resolves: paketo-buildpacks/php-dist#425

### CODE REVIEW

**Comment by sophiewigmore** [comment]
@till do you still need this PR?

**Comment by till** [comment]
@sophiewigmore no, sorry. I was meaning to try to get EasyCLA to work. But I'll try again next time. :D

**Comment by sophiewigmore** [comment]
@davidmirror-ops are there any updates on the easy CLA issues?

**Comment by davidmirror-ops** [comment]
@sophiewigmore the most recent advise from LF was to try again as in this case, CLA Manager and Approved Contributor are the same user, so an additional process needs to be completed by the user as documented here https://docs.linuxfoundation.org/lfx/easycla/v2-current/contributors/corporate-contributor#acknowledge-company-contribution

**Pull request closed without merging**
