### PR TITLE
Tidy up some things

### PR DESCRIPTION
**Pull request by joshuatcasey**
Tidy up some things

### CODE REVIEW

**Comment by joshuatcasey** [comment]
I chose `semver:minor` since this bumps the buildpack API version, although this should be invisible to consumers.

**Comment by robdimsdale** [comment]
@joshuatcasey this LGTM.

Just FYI the [Paketo semver guidelines](https://github.com/paketo-buildpacks/rfcs/blob/0a025596ecd1b8ab6775453f331177ac0243658e/text/0029-semantic-versioning.md#buildpack-general) suggest that a Buildpack API bump would be a major - but so far we've been treating Buildpack API bumps as a minor and I think I'm ok with that for this situation too, as we only just released v1.0.0 of this buildpack. Perhaps future API version bumps should be majors though? What do you think?

**Review by robdimsdale — DISMISSED** [review]

**Review by thitch97 — DISMISSED** [review]

**Comment by sophiewigmore** [comment]
@robdimsdale @thitch97 wait a minute - we've been treating API bumps as minors in other buildpacks because we hadn't cut a 1.0.0 release of those buildpacks yet. I think that this should be a major bump, we should follow the rules now that we're at a 1.0.0 release.

**Comment by robdimsdale** [comment]
@sophiewigmore sure - we could fast-follow `1.0.0` with `2.0.0`.

Or we could hold off bumping the API until we need it

**Comment by thitch97** [comment]
> @sophiewigmore sure - we could fast-follow `1.0.0` with `2.0.0`.
> 
> Or we could hold off bumping the API until we need it

I'm fine with either option here, leaning toward the latter. In my mind, the main changes introduced in API 0.8 weren't immediately relevant to this buildpack but @sophiewigmore makes a good point.

**Comment by joshuatcasey** [comment]
@paketo-buildpacks/php-maintainers I've updated this PR to (1) remove the buildpack API version bump, (2) rebase on latest, and (3) downgrade the semver to `patch`.

**Pull request merged**
