### PR TITLE
feat: Add OpenTelemetry extension to allow auto-instrumentation

### PR DESCRIPTION
**Pull request by cedricziel**
## Summary
Add the open telemetry php extension via pecl

## Use Cases

Enable observability for PHP apps built with the CNB

## Checklist

* [x] I have viewed, signed, and submitted the Contributor License Agreement.
* [x] I have linked issue(s) that this PR should close using keywords or the Github UI (See [docs](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue))
* [ ] I have added an integration test, if necessary.
* [ ] I have reviewed the [styleguide](https://github.com/paketo-buildpacks/community/blob/main/STYLEGUIDE.md) for guidance on my code quality.
* [x] I'm happy with the commit history on this PR (I have rebased/squashed as needed).

Closes: #785

### CODE REVIEW

**Comment by cedricziel** [comment]
@sophiewigmore - I'm not sure how to set the labels 🤔

**Comment by sophiewigmore** [comment]
Hi @cedricziel thanks for the PR. This change seems reasonable, however you'll need to add it to the extension lists in the files here as well: https://github.com/paketo-buildpacks/php-dist/tree/f0fcf6a87f5304092f826e192a287951d5ed3684/dependency/actions/compile/extensions-manifests. Make sure that the extension version is compatible with the version of PHP that corresponds to the extension file

**Comment by cedricziel** [comment]
@sophiewigmore done 👍 ext-opentelemetry is compatible with php >= 8 so I added it to all 3 manifests.

**Comment by sophiewigmore** [comment]
@cedricziel cool! thanks. can you please edit the PR to point to this new branch I've made? https://github.com/paketo-buildpacks/php-dist/tree/opentelemetry 

Since this affects the dependency compilation code, I want to push it to a branch on this repository so we can check it works in our dependency update Github action first. We can do that by triggering it off that branch and seeing all of our tests go green with the resulting dependencies

**Comment by sophiewigmore** [comment]
In thinking about doing that, I just realized we also test the compiled PHP dependency and check the extensions, so you may need to update the tests/fixtures here: https://github.com/paketo-buildpacks/php-dist/tree/95ca8b063cc3511e4dcb319d83dd802ec4997ef8/dependency/test

**Comment by cedricziel** [comment]
@sophiewigmore added them to the test apps and retargeted the branch

**Review by sophiewigmore — APPROVED** [review]

**Comment by sophiewigmore** [comment]
Testing here - https://github.com/paketo-buildpacks/php-dist/actions/runs/10852265782

**Comment by sophiewigmore** [comment]
@cedricziel re-testing here with an automation fix - https://github.com/paketo-buildpacks/php-dist/actions/runs/10905342607

**Pull request merged**
